name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * 6'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        xrootd-version: [5.5.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t xrootd --build-arg xrootd_version=$XROOTD_VERSION --progress=plain .
        env:
          PYTHON_VERSION: ${{ matrix.xrootd-version }}

      - name: Run tests
        run: docker run -h xrootdpyfs -t xrootd
